### ISSUE TITLE
Custom captcha

### ISSUE THREAD

**Issue by daychopan** [skotz/cbl-js#14]
Hey. I'm trying to fiddle around with your captcha solver. 

I tried to add this image for the program to solve:

https://imgur.com/QNJrBzP

without any luck. Do i need to strip down each character and store it as a master image, or how do i go about doing this?

**Comment by skotz** [comment]
Yes, the first step is to find a series of image operations that clean up the image so you can split it apart into individual characters. 

Without playing around with it too much myself, I'd suggest enabling perceptive_colorspace and then in your preprocess step playing around with thresholds for removeGray and colorRegions. Maybe start with one of the examples and edit it like this:
```
        var cbl = new CBL({
            preprocess: function(img) {
                img.removeGray(20);
                img.debugImage("debugPreprocessed");
                img.colorRegions(15);
                img.debugImage("debugPreprocessed");
            },
            perceptive_colorspace: true,
            blob_min_pixels: 50,
            pattern_width: 32,
            pattern_height: 32,
            blob_debug: "debugSegmented"
        });
        
        cbl.train("mpk.png");
```
Hope that helps!

**Comment by daychopan** [comment]
Thanks for the fast answer!!

**Comment by seantw** [comment]
I tried using the train() method, it must be entered one by one.
Is there any way to do batch training?

**Comment by skotz** [comment]
Currently the best way to do this would be looping through a training set and calling train() for each one. The C# version of the project can batch train on a folder of labeled samples, but in JS the browser doesn't have access to the file system so you have to manually enter a reference to each one.
