### ISSUE TITLE
Generate the model of the hash

### ISSUE THREAD

**Issue by teliz** [skotz/cbl-js#16]
hello, how can I generate the model of the hash to solve my captcha?
because of what I understand the .txt file has a hash that when loaded by the project understands * what each letter is. but my captcha is different and I need to train it and generate this new hash, but I do not know how to generate this hash

**Comment by skotz** [comment]
Just a few days ago I created a [model training sample](https://github.com/skotz/cbl-js/blob/master/starter/train.html) a that should hopefully provide some direction.

Essentially you need to call `saveModel()` after training to download your model.

**Comment by skotz** [comment]
Oh yeah, and there's a new [walkthrough ](https://github.com/skotz/cbl-js/blob/master/starter/quickstart.md) too.

**Comment by teliz** [comment]
work fine :)
