### ISSUE TITLE
using cbl with nodejs

### ISSUE THREAD

**Issue by teliz** [skotz/cbl-js#17]
hello, 
I'm trying to adapt cbl.js to work on nodejs, but I'm having a problem.

cbl does a getElementById () to get the image, but I currently have this image saved in a /src directory and as I run with the nodejs I do not have the DOM (I can try to use a package for virtual DOM, but I think it can not be best choice).

any tips?

**Comment by skotz** [comment]
Sorry, I'm not familiar enough with Node to have any suggestions. Maybe there's a package for image downloading or processing?

**Comment by teliz** [comment]
no problem.
😄
