### ISSUE TITLE
How about this one?

### ISSUE THREAD

**Issue by c4shm4st3r** [skotz/cbl-js#20]
hello, i have a harder challange, how would i use the library to presegment and actually solve  this single character captcha?

It is a single number from 1-9

I have a working method but i'd like to do with this method just for curiosity of how to get it working with javascript.

![verimage-477749927](https://user-images.githubusercontent.com/39650989/40576859-0065a74e-60f5-11e8-85a3-a4ab1cb0f91f.png)
![verimage-905817473](https://user-images.githubusercontent.com/39650989/40576863-083db8a8-60f5-11e8-93f6-65e601586b15.png)
![verimage-427168729](https://user-images.githubusercontent.com/39650989/40576867-0e901070-60f5-11e8-9969-07aa5681f40a.png)

Those images are just a small portion of the big dataset as an example. How would i get rid of the trashy background ?

Thanks in the future

**Comment by skotz** [comment]
What you really need here is an erosion filter, but unfortunately I haven't implemented that yet. You can try to get by with repeated blurring and binarization since that'll erode away edges until only the thickest lines (the numbers) are left. It's a hack, but the only other option is to implement more image manipulation methods.

```
var cbl = new CBL({
    preprocess: function(img) {
        img.blur(5);
        img.debugImage("debugPreprocessed");
        img.binarize(45);
        img.debugImage("debugPreprocessed");
        img.blur(5);
        img.debugImage("debugPreprocessed");
        img.binarize(45);
        img.debugImage("debugPreprocessed");
        img.blur(5);
        img.debugImage("debugPreprocessed");
        img.binarize(45);
        img.debugImage("debugPreprocessed");
        img.blur(5);
        img.debugImage("debugPreprocessed");
        img.binarize(45);
        img.debugImage("debugPreprocessed");
        img.blur(5);
        img.debugImage("debugPreprocessed");
        img.binarize(45);
        img.debugImage("debugPreprocessed");
        img.blur(5);
        img.debugImage("debugPreprocessed");
        img.binarize(45);
        img.debugImage("debugPreprocessed");
        img.blur(5);
        img.debugImage("debugPreprocessed");
        img.binarize(45);
        img.debugImage("debugPreprocessed");
        img.colorRegions(40, true);
        img.debugImage("debugPreprocessed");
    },
    character_set: "0123456789",
    blob_min_pixels: 1000,
    blob_max_pixels: 10000,
    pattern_width: 128,
    pattern_height: 128,
    pattern_maintain_ratio: true,
    allow_console_log: true,
    perceptive_colorspace: true,
    blob_debug: "debugSegmented",
    model_loaded: function() {
        document.getElementById("aSolve").style.display = "inline-block";
    }
});

cbl.train("3.png");
cbl.train("2.png");
cbl.train("1.png");
```
![3](https://user-images.githubusercontent.com/11474654/40577566-6241b7dc-60cd-11e8-8e54-ac9de5b54556.png)
![1](https://user-images.githubusercontent.com/11474654/40577568-640daaa8-60cd-11e8-89e2-79be0baa0905.png)
![2](https://user-images.githubusercontent.com/11474654/40577569-6609cb20-60cd-11e8-9e2d-841c954d4f08.png)
![3 png](https://user-images.githubusercontent.com/11474654/40577570-6aee3770-60cd-11e8-886a-21682f93be62.png)
![4](https://user-images.githubusercontent.com/11474654/40577572-6d66f1c2-60cd-11e8-9232-286df00ebba9.png)
![download](https://user-images.githubusercontent.com/11474654/40577573-6e5d4220-60cd-11e8-95fa-8a7365e9c7e7.png)

**Comment by c4shm4st3r** [comment]
just one more question, if the captcha character is not in the dataset, does it still detect similarities?

Imagine this, i have 30 different numbers 3's but the new one comes different from all of those, does it still detect similarities? how about inclinations?

**Comment by skotz** [comment]
If you train a model on several samples of every possible character (say, 5 of each digit), then new instances of that number (not used during training) should have a high likelihood of being correctly classified. Does that answer the question?

**Comment by skotz** [comment]
So... I added a convolution filter method, meaning now you can play around with erosion filters (Google "convolution kernels" to find common ones). If you get the latest from master, you can now do this:

```
var cbl = new CBL({
    preprocess: function(img) {
        img.debugImage("debugPreprocessed");
        img.convolute([ [  1,   1,   1,   1,   1,   1,   1],
						[  1,   1,   1,   1,   1,   1,   1],
						[  1,   1,   1,   1,   1,   1,   1],
						[  1,   1,   1, -48,   1,   1,   1],
						[  1,   1,   1,   1,   1,   1,   1],
						[  1,   1,   1,   1,   1,   1,   1], 
						[  1,   1,   1,   1,   1,   1,   1] ]);
        img.debugImage("debugPreprocessed");
		img.cropRelative(0, 5, 0, 5);
        img.debugImage("debugPreprocessed");
        img.colorRegions(2, true);
        img.debugImage("debugPreprocessed");
    },
    character_set: "0123456789",
    blob_min_pixels: 2000,
    blob_max_pixels: 10000,
    pattern_width: 32,
    pattern_height: 32,
    pattern_maintain_ratio: true,
    allow_console_log: true,
    perceptive_colorspace: true,
    blob_debug: "debugSegmented",
    model_loaded: function() {
        document.getElementById("aSolve").style.display = "inline-block";
    }
});
```

Which gives really good results, if I do say so myself.

![1](https://user-images.githubusercontent.com/11474654/40581060-84090676-6114-11e8-81b1-3e857786bb35.png)
![2](https://user-images.githubusercontent.com/11474654/40581061-8516d728-6114-11e8-98cd-39ee8e15846d.png)
![3](https://user-images.githubusercontent.com/11474654/40581062-85ef8c4e-6114-11e8-8ec9-f88d0a68ec2a.png)

Here's how it segments the three samples you had.

![c](https://user-images.githubusercontent.com/11474654/40581065-98609b20-6114-11e8-84cd-5a37a7c14472.png)
![b](https://user-images.githubusercontent.com/11474654/40581066-9937d7f2-6114-11e8-8bd2-9b5e5c183ef4.png)
![a](https://user-images.githubusercontent.com/11474654/40581067-99fc7882-6114-11e8-9455-0a4c5ab85be2.png)

**Comment by skotz** [comment]
I updated the library itself to add the new `convolute` command, so you'll need to download the latest version for that last snippet to work.
