### ISSUE TITLE
How to solve this captcha?

### ISSUE THREAD

**Issue by Thalisson** [skotz/cbl-js#29]
I tried many method it didn't work, can u help me for this? Many thanks!

![1](https://user-images.githubusercontent.com/3827329/48815356-66dafa80-ed25-11e8-84ae-9d5bd55bdcff.png)

![2](https://user-images.githubusercontent.com/3827329/48815357-66dafa80-ed25-11e8-8637-571067914a19.png)

![3](https://user-images.githubusercontent.com/3827329/48815358-66dafa80-ed25-11e8-9016-acf22582875a.png)

![4](https://user-images.githubusercontent.com/3827329/48815359-66dafa80-ed25-11e8-81bc-c8d307cde188.png)

![5](https://user-images.githubusercontent.com/3827329/48815360-67739100-ed25-11e8-9026-170778ab094b.png)

![6](https://user-images.githubusercontent.com/3827329/48815361-67739100-ed25-11e8-8e69-081922255742.png)

**Comment by Thalisson** [comment]
OK thank you for answering.
I'm going to run some tests.
What I got closer was the example
cryptographp

**Comment by Thalisson** [comment]
Poderia me ajudar , com algumas dicas de como usar a profundo a função `fixed_blob_locations` ?

**Comment by Thalisson** [comment]
Could you help me out with some tips on how to use the deep `fixed_blob_locations`?

**Comment by skotz** [comment]
Here's a working example:
https://github.com/skotz/cbl-js/blob/master/examples/paulebe/index.html

Basically you're specifying a list of rectangles in the image for each character. This only works when the characters are generally in the same place on each image, which for your images might just work. I'd give it a shot and see if it helps.

To get the locations, use an image editor and find the top left and lower right pixels around a character.

![image](https://user-images.githubusercontent.com/11474654/49050561-9072a680-f1a9-11e8-8791-2a8d58f97851.png)

In this example the upper left is (11, 8) and the lower right is (36, 33), so your first character would be something like this:

```
fixed_blob_locations: [
    { x1:  11, y1: 8, x2: 36, y2: 33 },
    /* another one for each character location */
],
```

You'll probably have to play around with the locations so it works for every image.

**Comment by Thalisson** [comment]
Great, thanks for your help.
I understood how this works.
I will play a bit and give a certain classification to the code and the result.

Thank you very much
