### ISSUE TITLE
Can you please help with this one?

### ISSUE THREAD

**Issue by HarutEnoqyan** [skotz/cbl-js#35]
![captcha](https://user-images.githubusercontent.com/39312523/63917928-b71d8080-ca4c-11e9-88d7-4df3251c7a6a.png)

**Comment by skotz** [comment]
What have you tried so far? You could take a look at [this example](https://github.com/skotz/cbl-js/tree/master/examples/elvincth) which also deals with lines.

**Comment by HarutEnoqyan** [comment]
I have tried this
preprocess: function(img) {
                img.debugImage("debugPreprocessed");
                img.convolute([ [0, 1, 0],
                                [0, 1, 0],
                                [0, 0, 0], ], 0.5);
                img.invert();
                img.binarize(180);
                img.colorRegions(60, false, 1);
                img.debugImage("debugPreprocessed");
            },
            model_file: "NEWMODEL.txt",
            character_set: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
            blob_min_pixels: 50,
            blob_max_pixels: 200,
            pattern_width: 25,
            pattern_height: 25,
            allow_console_log: true,
            perceptive_colorspace: true,

**Comment by skotz** [comment]
You'll want to remove the `model_file` setting until you've trained the model. Also, you'll need a lot more example images to really find a set of preprocessing commands that work for this system.
