### ISSUE TITLE
Use image file instead of img html node?

### ISSUE THREAD

**Issue by JBowen** [skotz/cbl-js#37]
Is there a way I can just have this solve a captcha from the downloaded image instead of through an img element? I'm doing some cross domain stuff, and I want to avoid opening an iframe as it slows things down.

**Comment by skotz** [comment]
You mean open an image file without directly or indirectly loading it with an img tag? Right now I believe it only works if the image is already referenced in an img tag, or if you call `cbl.solve` with the path to the image (which internally creates an img tag).
