### ISSUE TITLE
Help to solve this captcha.

### ISSUE THREAD

**Issue by lakudo** [skotz/cbl-js#40]
Hi, I am trying to recognize this captcha. and  came across a problem.
captcha :
![img1](https://f000.backblazeb2.com/file/canicula/ImgURL/1.jpg)
![img2](https://f000.backblazeb2.com/file/canicula/ImgURL/2.jpg)
![img3](https://f000.backblazeb2.com/file/canicula/ImgURL/3.jpg)
![img4](https://f000.backblazeb2.com/file/canicula/ImgURL/4.jpg)
![img5](https://f000.backblazeb2.com/file/canicula/ImgURL/5.jpg)
When run train.html,

           var cbl = new CBL({
              preprocess: function(img) {
                img.binarize(32);
                img.debugImage("debugPreprocessed");
                img.blur(1);
                img.debugImage("debugPreprocessed");
                img.binarize(255);
                img.debugImage("debugPreprocessed");
                img.colorRegions(40, true);
                img.debugImage("debugPreprocessed");
            },
            character_set: "0123456789",
            model_file: "model.txt",
            blob_min_pixels: 40,
            blob_max_pixels: 350,
            pattern_width: 24,
            pattern_height: 24,
            pattern_maintain_ratio: true,
            allow_console_log: true,
            perceptive_colorspace: true,
            blob_debug: "debugSegmented"
        });
The result of 16 sample training is :
![train](https://f000.backblazeb2.com/file/canicula/ImgURL/train.jpg)

Then, update model.txt and  solve.html file, it can't fully identify the captcha.
Target captcha:
![img6](https://f000.backblazeb2.com/file/canicula/ImgURL/6.jpg)
Result:
![solve](https://f000.backblazeb2.com/file/canicula/ImgURL/solve.jpg)

        var cbl = new CBL({
            preprocess: function(img) {
                img.binarize(100);
                img.blur(1);
                img.binarize(220);
                img.colorRegions(40);
            },
            /* Load the model we saved during training. */
            model_file: "model.txt",
            character_set: "0123456789",
            blob_min_pixels: 40,
            blob_max_pixels: 350,
            pattern_width: 24,
            pattern_height: 24,
            perceptive_colorspace: true,
            /* Define a method that fires immediately after successfully loading a saved model. */
            model_loaded: function() {
                // Don't enable the solve button until the model is loaded.
                document.getElementById('solve').style.display = "block";
            }
        });   

Is it because of Not enough sample training or other else's ?Could you help me to fix it? Thanks!

**Comment by skotz** [comment]
Looks like you did a good job segmenting. Are you using the same image preprocessing steps in both the trainer and solver? The two scripts you have above have slightly different values. The solver `preprocess` steps need to be exactly the same as the trainer steps used when the model was generated.

If that doesn't fix it, then one thing you could do is load your model.txt file and then do a `cbl.visualizeModel("theIdOfSomeDiv")` and see if it outputs all of the patters you're expecting.

**Comment by lakudo** [comment]
> Looks like you did a good job segmenting. Are you using the same image preprocessing steps in both the trainer and solver? The two scripts you have above have slightly different values. The solver `preprocess` steps need to be exactly the same as the trainer steps used when the model was generated.

Sorry,just double check train file, It's a typo. Both are using the same image preprocessing steps preprocessing steps,

            preprocess: function(img) {
                img.binarize(100);
                img.debugImage("debugPreprocessed");
                img.blur(1);
                img.debugImage("debugPreprocessed");
                img.binarize(220);
                img.debugImage("debugPreprocessed");
                img.colorRegions(40, true);
                img.debugImage("debugPreprocessed");
            },
            character_set: "0123456789",
            model_file: "model.txt",
            blob_min_pixels: 40,
            blob_max_pixels: 350,
            pattern_width: 24,
            pattern_height: 24,
            pattern_maintain_ratio: true,
            allow_console_log: true,
            perceptive_colorspace: true,
            blob_debug: "debugSegmented"
        });


> 
> If that doesn't fix it, then one thing you could do is load your model.txt file and then do a `cbl.visualizeModel("theIdOfSomeDiv")` and see if it outputs all of the patters you're expecting.
A little bit confused, How to do a `cbl.visualizeModel("theIdOfSomeDiv")`?    on page of solver  run `cbl.visualizeModel("theIdOfSomeDiv")` in console ?

**Comment by skotz** [comment]
First you'll need to add a new div with an id to the page like `<div id="test"></div>` and then yes, run `cbl.visualizeModel("test")` in the console. That should output a bunch of the trained images to that div.

**Comment by lakudo** [comment]
> cbl.visualizeModel("test")




> First you'll need to add a new div with an id to the page like `<div id="test"></div>` and then yes, run `cbl.visualizeModel("test")` in the console. That should output a bunch of the trained images to that div.

Just add a div id and run cbl.visualizeModel("test"), it seems to be good.
![debug](https://f000.backblazeb2.com/file/canicula/ImgURL/debug.jpg)


    <div id="test" class="main">
        <img id="captcha" src="6.jpg" />
        <br />
        <input type="text" id="solution">
        <br />
        <a href="javascript: void(0)" id="solve" onclick="solve()" style="display: none">Solve!</a>
    </div>
    <script>
        var cbl = new CBL({
            preprocess: function(img) {
                img.binarize(100);
                img.blur(1);
                img.binarize(220);
                img.colorRegions(40);
            
            },
            /* Load the model we saved during training. */
            model_file: "model.txt",
            character_set: "0123456789",
            blob_min_pixels: 40,
            blob_max_pixels: 350,
            pattern_width: 24,
            pattern_height: 24,
            //perceptive_colorspace: true,
            /* Define a method that fires immediately after successfully loading a saved model. */
            model_loaded: function() {
                // Don't enable the solve button until the model is loaded.
                document.getElementById('solve').style.display = "block";
            }
        });    
        
        var solve = function() {
            // Using the saved model, attempt to find a solution to a specific image.
            cbl.solve("captcha").done(function (solution) {
                // Upon finding a solution, fill the solution textbox with the answer.
                document.getElementById('solution').value = solution;
                alert(solution)
            });
        }
    </script>

**Comment by skotz** [comment]
That looks pretty good. Maybe one of the samples is mislabeled. Try doing this:

```
cbl.condenseModel();
cbl.sortModel();
cbl.visualizeModel("test");
cbl.saveModel();
```

And then saving it as a new model file. This will combine similar patterns and hopefully help eliminate any one-off errors in classification.

**Comment by lakudo** [comment]
Try it again following your steps, update the new condesed model file which looks good,but it still don't work.
![condense](https://f000.backblazeb2.com/file/canicula/ImgURL/condense.jpg) 
![debug2](https://f000.backblazeb2.com/file/canicula/ImgURL/debug2.jpg)
I try some new captchas which incluld number "1", I found a wired  incident that all "1"   became to "3".
![debug3](https://f000.backblazeb2.com/file/canicula/ImgURL/debug3.jpg)
![debug4](https://f000.backblazeb2.com/file/canicula/ImgURL/debug4.jpg)

**Comment by skotz** [comment]
Yeah that's really odd. To debug it further I'd need a copy of your model.

**Comment by lakudo** [comment]
[condensed model.txt](https://f000.backblazeb2.com/file/canicula/condensed_model.txt)
[uncondensed model.txt](https://f000.backblazeb2.com/file/canicula/uncondensed_model.txt)

**Comment by skotz** [comment]
I compared the patterns with the segmented letters and noticed that you're scaling them during training but stretching them during solving.

![image](https://user-images.githubusercontent.com/11474654/67147787-c6a39380-f25d-11e9-8a41-259dd6f5543e.png)

If you add this line to your solver just like you have with your trainer, it works great.

```
pattern_maintain_ratio: true
```

![image](https://user-images.githubusercontent.com/11474654/67147797-e1760800-f25d-11e9-9551-15f2b3dec187.png)

Hopefully that'll do it!

**Comment by lakudo** [comment]
Yeah! I missed an attribution " pattern_maintain_ratio:ture" in solving while set to "ture"in training. Much obliged.
By the way, if want to solve cross-origin captcha,which is generated by other website, how can I modify it?
