### ISSUE TITLE
Do you think that this captcha is breakable?

### ISSUE THREAD

**Issue by nicoworq** [skotz/cbl-js#67]
Hi! Great library, thanks for sharing it! 

I'm dealing with this captcha: 

![1](https://user-images.githubusercontent.com/9120494/123321030-de3e1f80-d508-11eb-8974-016a80d0ec4e.jpg)
![2](https://user-images.githubusercontent.com/9120494/123321035-df6f4c80-d508-11eb-80bd-c228e82d524b.jpg)
![3](https://user-images.githubusercontent.com/9120494/123321039-df6f4c80-d508-11eb-8a0c-9c27f1a8d5d7.jpg)
![4](https://user-images.githubusercontent.com/9120494/123321040-e007e300-d508-11eb-8ec8-9e1c4913ea67.jpg)
![5](https://user-images.githubusercontent.com/9120494/123321041-e007e300-d508-11eb-8f1a-a498d93b928c.jpg)
![6](https://user-images.githubusercontent.com/9120494/123321043-e0a07980-d508-11eb-8b00-ab09981e677b.jpg)
![7](https://user-images.githubusercontent.com/9120494/123321045-e0a07980-d508-11eb-93db-73fd61aef525.jpg)
![8](https://user-images.githubusercontent.com/9120494/123321047-e1391000-d508-11eb-8c3b-35bd939faddf.jpg)
![9](https://user-images.githubusercontent.com/9120494/123321049-e1391000-d508-11eb-947d-aa0515175a6c.jpg)
![10](https://user-images.githubusercontent.com/9120494/123321051-e1d1a680-d508-11eb-8bd5-9214345e2602.jpg)

Do you think that is possible to train a model based on this captcha? 

Thanks a lot !

**Comment by skotz** [comment]
Some of the digits are difficult even for a human, but there are a couple of flaws in the system that you can use to your advantage.
- Always exactly 6 digits
- Only 10 different characters (use `character_set: "0123456789"`)
- No horizontal translation (maybe try `fixed_blob_locations` like [this](https://github.com/skotz/cbl-js/blob/master/examples/paulebe/index.html) or maybe `exact_characters: 6, exact_characters_width: 7` like [this](https://github.com/skotz/cbl-js/blob/master/examples/alawiggle/index.html))

![image](https://user-images.githubusercontent.com/11474654/123521301-6fcd9e80-d67b-11eb-959d-5b8c4651e633.png)

**Comment by nicoworq** [comment]
Thanks a lot for your reply! 🍺🍺
